# Generated by Django 3.2.16 on 2022-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out of Delivery', 'out of Delivery')], max_length=200, null=True),
        ),
    ]
