# Generated by Django 3.2.16 on 2022-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out of Delivery', 'out of Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
